// <auto-generated />
using HAN.ADB.RDT.DataMigrationTool.DataAccess.SqlLite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HAN.ADB.RDT.DataMigrationTool.Migrations
{
    [DbContext(typeof(ProgressContext))]
    partial class ProgressContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("HAN.ADB.RDT.DataMigrationTool.Core.SqlLite.PostProgress", b =>
                {
                    b.Property<int>("LastInsertedId")
                        .HasColumnType("INTEGER");

                    b.ToTable("PostProgresses");
                });

            modelBuilder.Entity("HAN.ADB.RDT.DataMigrationTool.Core.SqlLite.UserProgress", b =>
                {
                    b.Property<int>("LastInserted")
                        .HasColumnType("INTEGER");

                    b.ToTable("UserProgresses");
                });
#pragma warning restore 612, 618
        }
    }
}
